import Link from "next/link";

export default function Home() {
  return <main className="mx-auto max-w-6xl px-6">
    <header className="flex items-center justify-between border-b py-6"><Link href="/" className="text-2xl font-semibold tracking-tight">Clerq</Link><nav aria-label="Main" className="flex gap-5 text-sm"><Link href="/login" className="underline underline-offset-4">Sign in</Link><Link href="/dashboard" className="underline underline-offset-4">Open workspace</Link></nav></header>
    <section className="max-w-3xl space-y-7 py-20 sm:py-28"><p className="text-sm font-medium uppercase tracking-widest text-muted-foreground">Receipts · Records · Reconciliation</p><h1 className="text-4xl font-semibold leading-tight tracking-tight sm:text-6xl">Receipts and bank transactions, brought together.</h1><p className="max-w-2xl text-lg leading-relaxed text-muted-foreground">Collect your receipts, import a bank statement and review matches in one workspace. Keep the original documents close and make missing paperwork easier to find.</p><div className="flex flex-wrap gap-3"><Link href="/register" className="rounded-md bg-primary px-5 py-3 font-medium text-primary-foreground">Create your workspace</Link><a href="#how-it-works" className="rounded-md border px-5 py-3 font-medium">See how it works</a></div></section>
    <section id="how-it-works" className="space-y-8 border-t py-14"><h2 className="text-2xl font-semibold">From scattered receipts to reviewed records</h2><div className="grid gap-6 md:grid-cols-3">{[
      ["01", "Collect your receipts", "Upload PDF or image receipts, or forward attachments to your configured organisation address. Original files stay in your private vault."],
      ["02", "Import your statement", "Upload a bank CSV and confirm its columns, currency and date format. Review import results and skipped duplicates."],
      ["03", "Review and export", "Check suggested matches, correct unclear receipt details and download a monthly pack with CSV records and original matched receipts."],
    ].map(([number, title, body]) => <article key={number} className="space-y-4 rounded-lg border p-6"><p className="text-sm text-muted-foreground">{number}</p><h3 className="text-lg font-semibold">{title}</h3><p className="leading-relaxed text-muted-foreground">{body}</p></article>)}</div></section>
    <section className="grid gap-8 border-t py-14 md:grid-cols-2"><div><h2 className="text-2xl font-semibold">You stay in control of the details.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Extraction helps populate receipt fields. Unclear values and uncertain matches need your review before you rely on them.</p></div><div className="space-y-5"><details className="rounded border p-4"><summary className="cursor-pointer font-medium">Which receipt files can I upload?</summary><p className="mt-3 text-muted-foreground">PDF, PNG, JPEG and WebP files up to 10 MB each. You can select up to 10 files at a time.</p></details><details className="rounded border p-4"><summary className="cursor-pointer font-medium">Does Clerq connect directly to my bank?</summary><p className="mt-3 text-muted-foreground">Bank transactions are imported from CSV files. Choose the currency and confirm the column mapping before import.</p></details><details className="rounded border p-4"><summary className="cursor-pointer font-medium">What is in the monthly export?</summary><p className="mt-3 text-muted-foreground">A ZIP containing a reconciliation CSV and original matched receipt files, selected by reconciliation month. It is a record pack, not a submitted tax return.</p></details></div></section>
    <footer className="flex flex-wrap items-center justify-between gap-4 border-t py-8 text-sm"><p>Clerq · Keep your records together.</p><Link href="/register" className="underline underline-offset-4">Get started</Link></footer>
  </main>;
}
