import Link from "next/link";
import { ArrowRight, Check, X, UploadCloud, FileSpreadsheet, Link2, Archive, ShieldCheck, Eye, Globe, LockKeyhole, FileText, Building2, Users, Plus } from "lucide-react";
import { LandingWorkbench } from "@/components/landing-workbench";

const features = [
  { eyebrow: "COLLECT · EXTRACT · REVIEW", title: "Automated receipt ingestion & extraction", body: "Bring scattered receipts into one private vault. Upload PDFs and images, or forward supported attachments to your organisation address.", points: ["Text PDFs, scanned PDFs, PNG, JPEG and WebP", "Saved originals with queued extraction progress", "Manual review when fields are unclear"], icon: UploadCloud },
  { eyebrow: "YOUR STATEMENT · YOUR STRUCTURE", title: "Bank statement CSV mapping", body: "Import your bank’s CSV export and confirm how to read it. Keep control of dates, currency and debit or credit conventions.", points: ["Choose date, description, amount and credit columns", "Australian DMY and US MDY date formats", "Import results with duplicate and invalid-row counts"], icon: FileSpreadsheet },
  { eyebrow: "AUTOMATIC MATCHES · HUMAN REVIEW", title: "Reconciliation workspace & match confidence", body: "Compare expense payments with receipts side by side. Clear matches can reconcile automatically; uncertain suggestions stay available for your review.", points: ["Match amounts, dates and vendor names", "Confirm suggestions or make a manual match", "Flag missing receipts and dismiss unsuitable pairs"], icon: Link2 },
  { eyebrow: "ORIGINAL FILES · REVIEWED RECORDS", title: "Monthly reconciliation export packs", body: "Keep a month’s matched records together. Download a ZIP containing a reconciliation CSV and the original supporting documents.", points: ["Select the month the match was recorded", "Original PDFs and images retain their file formats", "Up to 200 matched receipts and 100 MB of originals"], icon: Archive },
];
const faqs = [
  ["What bank statement formats does Clerq support?", "Import a CSV export up to 4 MB and 10,000 rows. Confirm the column mapping, date order, three-letter currency and sign convention before importing."],
  ["Which receipt files can I upload?", "PDF, scanned PDF, PNG, JPEG and WebP files up to 10 MB each. You can select up to 10 files at a time."],
  ["How does receipt extraction work?", "Clerq reads the document and extracts receipt fields. Uploading saves the original first; extraction happens in the background. Unreadable fields and failed extraction need manual review."],
  ["Does Clerq connect directly to my bank?", "Bank transactions are imported from CSV files. Clerq does not require your bank login credentials or connect to a live bank feed."],
  ["What is in the monthly export?", "A ZIP containing a reconciliation CSV and original matched receipt files, selected by reconciliation month. The pack can contain up to 200 matched receipts and 100 MB of originals."],
  ["Can I work with multiple currencies?", "Records display explicit currency codes. Matching requires the receipt and bank transaction to use the same currency; Clerq does not convert currencies."],
];
function Brand() { return <span className="lp-brand"><span className="lp-brand-icon"><span /></span><strong>clerq</strong></span>; }
function FeaturePreview({ index }: { index: number }) {
  if (index === 0) return <div className="lp-feature-preview"><div className="lp-preview-heading"><span>RECEIPT VAULT</span><span className="lp-status lp-status-matched">SAVED ORIGINAL</span></div><div className="lp-mini-grid"><div><small>Vendor</small><strong>Adobe</strong></div><div><small>Date</small><strong>24 Sep 2026</strong></div><div><small>Total</small><strong>AUD 49.99</strong></div><div><small>Source</small><strong>Web upload</strong></div><div><small>Status</small><strong>Unmatched</strong></div><div><small>Category</small><strong>Software</strong></div></div><div className="lp-file-row"><FileText size={18} /><span>adobe-receipt.pdf<small>Original document · example record</small></span><Check size={16} /></div></div>;
  if (index === 1) return <div className="lp-feature-preview"><div className="lp-preview-heading"><span>MAP YOUR CSV COLUMNS</span><span>bank-september.csv</span></div>{[["Date", "Transaction date"], ["Description", "Narration"], ["Amount / debit", "Debit amount"], ["Currency", "AUD"]].map(([label, value]) => <div className="lp-mapping-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}<div className="lp-preview-caption">DMY / Australia · Confirm before import</div></div>;
  if (index === 2) return <div className="lp-feature-preview"><div className="lp-preview-heading"><span>SUGGESTED MATCH</span><span className="lp-status lp-status-suggested">REVIEW</span></div><div className="lp-match-row"><small>Bank transaction</small><strong>ATLASSIAN SOFTWARE</strong><span>AUD 82.50</span></div><div className="lp-match-row"><small>Receipt</small><strong>Atlassian</strong><span>AUD 82.50</span></div><div className="lp-demo-note"><Link2 size={14} /> Same amount · 1 day apart · review vendor</div><Link href="/dashboard" className="lp-mini-action">Open reconciliation <ArrowRight size={13} /></Link></div>;
  return <div className="lp-feature-preview"><div className="lp-preview-heading"><span>MONTHLY RECONCILIATION PACK</span><span>SEP 2026</span></div>{["Reconciliation_Report_2026-09.csv", "receipts/adobe-receipt.pdf", "receipts/aws-receipt.png"].map(file => <div className="lp-file-row" key={file}><FileText size={16} /><span>{file}</span><Check size={14} /></div>)}<p className="lp-preview-caption">Illustrative archive · originals and CSV together</p><Link href="/dashboard" className="lp-mini-action">Open monthly export <Archive size={13} /></Link></div>;
}
export default function Home() {
  return <div className="lp-shell"><header className="lp-nav"><div className="lp-nav-inner"><Link href="/" aria-label="Clerq home"><Brand /></Link><nav aria-label="Main"><a href="#product">Product</a><a href="#solutions">Solutions</a><a href="#workflow">Workflow</a><a href="#faq">Resources</a></nav><div className="lp-nav-actions"><span className="lp-locale">● en-AU</span><Link href="/login">Sign in</Link><Link href="/register" className="lp-button lp-button-small">Create workspace <ArrowRight size={13} /></Link></div></div></header>
    <main id="main-content"><section className="lp-hero"><div className="lp-mesh" aria-hidden="true" /><div className="lp-hero-copy"><p className="lp-hero-pill"><span />RECEIPT INGESTION & RECONCILIATION</p><h1>Receipts and bank statements,<br />reconciled with precision.</h1><p>Collect receipts, import bank transactions and review the details between them. A clear workspace for business owners, agencies and bookkeepers.</p><div className="lp-hero-actions"><Link href="/register" className="lp-button">Create your workspace <ArrowRight size={15} /></Link><a href="#workbench-preview" className="lp-button lp-button-outline">Explore the workspace preview</a></div><p className="lp-hero-note"><Check size={13} />Private originals · CSV imports · Matches you can review</p></div><LandingWorkbench /></section>
    <div className="lp-capabilities-strip"><div className="lp-container"><p>YOUR MONTH-END RECORDS,<br /><strong>BROUGHT TOGETHER.</strong></p><div>{["PRIVATE RECEIPT VAULT", "BANK CSV IMPORT", "MATCH REVIEW", "MONTHLY EXPORT"].map(text => <span key={text}><Check size={12} />{text}</span>)}</div></div></div>
    <section className="lp-section lp-container"><div className="lp-section-title"><p className="lp-mono">LESS CHASING. MORE CLARITY.</p><h2>The monthly paperwork scramble, resolved.</h2><p>Move from scattered documents to a workspace that keeps the details close.</p></div><div className="lp-comparison"><article><h3>The manual status quo</h3>{["Receipts spread across inboxes and folders", "Bank rows checked against files one at a time", "Unclear totals and missing dates need investigation", "Supporting documents gathered again at month-end"].map(text => <p key={text}><X size={14} />{text}</p>)}</article><article><h3>The Clerq workflow</h3>{["Upload or forward receipts to one organisation vault", "Extract document fields for review", "Import a statement and review matching suggestions", "Export matched records with their original files"].map(text => <p key={text}><Check size={14} />{text}</p>)}</article></div></section>
    <section id="product" className="lp-features lp-container">{features.map(({ eyebrow, title, body, points, icon: Icon }, index) => <article key={title} className={`lp-feature ${index % 2 ? "lp-feature-reverse" : ""}`}><div className="lp-feature-copy"><p className="lp-mono">{eyebrow}</p><h2>{title}</h2><p>{body}</p><ul>{points.map(point => <li key={point}><Icon size={13} />{point}</li>)}</ul></div><FeaturePreview index={index} /></article>)}</section>
    <section id="solutions" className="lp-section lp-section-tint"><div className="lp-container"><div className="lp-section-title"><p className="lp-mono">BUILT AROUND THE PAPERWORK</p><h2>Designed for teams handling real paperwork.</h2><p>Keep receipts, payments and supporting records in a shared organisation workspace.</p></div><div className="lp-three-grid">{[[Building2, "Agency owners & operators", "Collect software, contractor and operating receipts throughout the month. Review missing paperwork alongside imported payments."], [FileSpreadsheet, "Bookkeepers", "Map client bank exports, review extracted fields and confirm the receipt and payment pairs that belong together."], [Users, "Organisation administrators", "Keep organisation records in one workspace and activate receipt forwarding when the receiving service is configured."]].map(([Icon, title, body]) => { const CardIcon = Icon as typeof Users; return <article className="lp-card" key={String(title)}><CardIcon size={20} /><h3>{String(title)}</h3><p>{String(body)}</p><Link href="/register">Create a workspace <ArrowRight size={13} /></Link></article>; })}</div></div></section>
    <section id="workflow" className="lp-section lp-container"><div className="lp-section-title"><p className="lp-mono">FROM DOCUMENTS TO RECORDS</p><h2>Four simple steps to reviewed records.</h2></div><div className="lp-four-grid">{[["01", "Create your workspace", "Register, sign in and create your organisation."], ["02", "Collect receipts", "Upload documents or forward supported attachments."], ["03", "Import a bank CSV", "Confirm the columns, dates, currency and sign convention."], ["04", "Reconcile & export", "Review matches and download a monthly record pack."]].map(([number, title, body]) => <article className="lp-card" key={number}><span className="lp-step">{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section id="security" className="lp-section lp-section-tint"><div className="lp-container"><div className="lp-section-title lp-title-left"><p className="lp-mono">CLEAR BOUNDARIES</p><h2>Private records. Transparent workflows.</h2><p>Understand what Clerq does with your documents and where your review matters.</p></div><div className="lp-two-grid">{[[ShieldCheck, "Organisation access checks", "Workspace pages and actions check membership. Receipt originals are stored privately and opened through authorised file links."], [Eye, "Extraction with human review", "Saved uploads may still be processing. Unclear values and uncertain matches stay available for review."], [Globe, "Explicit currency codes", "Amounts carry their currency. Matching requires the same currency; conversion is outside the current workflow."], [LockKeyhole, "No bank login required", "Import bank exports as CSV files. No live bank feed or bank credentials are required."]].map(([Icon, title, body]) => { const CardIcon = Icon as typeof Eye; return <article className="lp-card lp-info-card" key={String(title)}><CardIcon size={17} /><div><h3>{String(title)}</h3><p>{String(body)}</p></div></article>; })}</div></div></section>
    <section className="lp-section lp-container"><div className="lp-section-title"><p className="lp-mono">PRODUCT TRANSPARENCY</p><h2>Supported inputs. Clear boundaries.</h2><p>Plan your workflow around the features available in the application.</p></div><div className="lp-comparison lp-support"><article><h3>Available in Clerq</h3>{["PDF and image receipt uploads", "Forwarded receipt attachments", "CSV column mapping and import", "Automatic matches and manual review", "CSV and original-file ZIP exports"].map(text => <p key={text}><Check size={13} />{text}</p>)}</article><article><h3>Outside the current workflow</h3>{["Live bank connections", "Currency conversion", "Income matching", "Tax return submission", "Scheduled or emailed exports"].map(text => <p key={text}><span className="lp-boundary-dot" />{text}</p>)}</article></div></section>
    <section className="lp-section lp-section-tint"><div className="lp-container"><div className="lp-section-title"><p className="lp-mono">ONE CONNECTED WORKFLOW</p><h2>Everything you need to keep the month together.</h2><p>Collect the records. Review the details. Keep the supporting files.</p></div><div className="lp-three-grid">{[[UploadCloud, "Collect", "One private receipt vault", ["Upload up to 10 files at once", "10 MB per receipt", "Original PDF and image files"]], [Link2, "Reconcile", "Payments beside receipts", ["CSV imports up to 10,000 rows", "Suggestions you can confirm", "Manual matching and notes"]], [Archive, "Export", "A monthly record pack", ["Reconciliation CSV", "Matched original documents", "200 receipts / 100 MB limit"]]].map(([Icon, title, description, points]) => { const CardIcon = Icon as typeof Archive; return <article className="lp-card lp-workflow-card" key={String(title)}><CardIcon size={20} /><h3>{String(title)}</h3><p>{String(description)}</p><ul>{(points as string[]).map(point => <li key={point}><Check size={13} />{point}</li>)}</ul><Link href="/dashboard" className="lp-button lp-button-small">Open workspace <ArrowRight size={13} /></Link></article>; })}</div></div></section>
    <section id="faq" className="lp-section lp-container"><div className="lp-section-title"><p className="lp-mono">COMMON QUESTIONS</p><h2>Frequently asked questions</h2></div><div className="lp-faq">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={15} /></summary><p>{answer}</p></details>)}</div></section>
    <section className="lp-section lp-section-tint"><div className="lp-container"><div className="lp-final-card"><p className="lp-mono">MAKE ROOM FOR A CLEARER MONTH-END</p><h2>Bring your receipts and bank<br />statements into one place.</h2><p>Start with your organisation, add your records and review the matches.</p><div className="lp-hero-actions"><Link href="/register" className="lp-button">Create your workspace <ArrowRight size={14} /></Link><Link href="/login" className="lp-button lp-button-outline">Already registered? Sign in</Link></div><p className="lp-hero-note">Your documents · Your review · Your records</p></div></div></section></main>
    <footer className="lp-footer lp-container"><div className="lp-footer-grid"><div><Brand /><p>Receipts, bank transactions and supporting records, brought together.</p></div><div><h3>Product</h3><a href="#product">Receipt extraction</a><a href="#workbench-preview">Reconciliation preview</a><a href="#workflow">Monthly exports</a></div><div><h3>Solutions</h3><a href="#solutions">Agencies</a><a href="#solutions">Bookkeepers</a><a href="#solutions">Administrators</a></div><div><h3>Workspace</h3><Link href="/register">Get started</Link><Link href="/login">Sign in</Link><Link href="/dashboard">Open workspace</Link></div></div><div className="lp-footer-bottom"><span>Clerq · Keep your records together.</span><a href="#faq">Questions & answers</a><span>Australian English · Explicit currency codes</span></div></footer>
  </div>;
}
