"use client";
import { useMemo } from "react";
import { flexRender, getCoreRowModel, getPaginationRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";

export function DataTable<T extends { id: string }>({ rows, columns, selectedId, onSelect, serverPaginated = false }: { serverPaginated?: boolean; rows: T[]; columns: ColumnDef<T>[]; selectedId?: string; onSelect: (row: T) => void }) {
  const data = useMemo(() => rows, [rows]);
  // TanStack exposes mutable table APIs intentionally; do not compiler-memoise.
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({ data, columns, getCoreRowModel: getCoreRowModel(), getPaginationRowModel: getPaginationRowModel(), manualPagination: serverPaginated, getRowId: row => row.id, initialState: { pagination: { pageSize: 20 } } });
  return <>{rows.length ? <div className="reconcile-table-wrap"><table className="reconcile-table"><thead>{table.getHeaderGroups().map(group => <tr key={group.id}><th className="reconcile-select-heading">Select</th>{group.headers.map(header => <th key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id} className={row.id === selectedId ? "reconcile-row-selected" : ""} onClick={() => onSelect(row.original)}><td><button aria-label={`Select row ${row.index + 1}`} aria-pressed={row.id === selectedId} className={`reconcile-select-button ${row.id === selectedId ? "reconcile-select-active" : ""}`} onClick={event => { event.stopPropagation(); onSelect(row.original); }}>{row.id === selectedId ? "✓" : ""}</button></td>{row.getVisibleCells().map(cell => <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div> : <div className="reconcile-table-empty">No records match this filter.</div>}{!serverPaginated && rows.length > 0 && <div className="reconcile-local-pagination"><button onClick={() => table.previousPage()} disabled={!table.getCanPreviousPage()}>Previous</button><span>Page {table.getState().pagination.pageIndex + 1} of {Math.max(1, table.getPageCount())}</span><button onClick={() => table.nextPage()} disabled={!table.getCanNextPage()}>Next</button></div>}</>;
}
